namespace DataAccess.Domain.Models;

public partial class Asset
{
    public decimal Id { get; set; }
    public decimal? Num { get; set; }
    public string? Arname { get; set; }
    public decimal? Cost { get; set; }
    public DateTime? Dtstart { get; set; }
    public decimal? Assetid { get; set; }
    public decimal? Destroyid { get; set; }
    public decimal? Payid { get; set; }
    public decimal? Destroyperc { get; set; }
    public decimal? Destroyval { get; set; }
    public string? State { get; set; }
    public string? Site { get; set; }
    public string? Adress { get; set; }
    public decimal? Workid { get; set; }
    public decimal? Custid { get; set; }
    public decimal? Billnum { get; set; }
    public decimal? Pay { get; set; }
    public decimal? Credit { get; set; }
    public decimal? Debit { get; set; }
    public decimal? Balance { get; set; }
    public DateTime? Dt { get; set; }
    public string? Lbl { get; set; }
    public decimal? Capitalid { get; set; }
    public decimal? Remain { get; set; }
    public decimal? Days { get; set; }
    public decimal? Totaldestroy { get; set; }
    public bool? Active { get; set; }
    public decimal? Regnum { get; set; }
    public bool? Isnew { get; set; }
    public decimal? DistroyDiscountId { get; set; }
    public bool? IsRent { get; set; }
    public DateTime? Fromtime { get; set; }
    public DateTime? Totime { get; set; }
    public decimal? CostId { get; set; }
    public decimal? PayType { get; set; }
    public decimal? TaskId { get; set; }
    public decimal? Total { get; set; }
    public decimal? BranchId { get; set; }
    public string? Txt1 { get; set; }
    public string? Txt2 { get; set; }
    public string? Txt3 { get; set; }
    public string? Txt4 { get; set; }
    public string? Txt5 { get; set; }
    public string? Txt6 { get; set; }
    public string? Txt7 { get; set; }
    public string? Txt8 { get; set; }
    public bool? FixedPrice { get; set; }
    public bool? IscustomerExpense { get; set; }
    public decimal? Price { get; set; }
    public decimal? OpenQty { get; set; }
    public decimal? OpenCost { get; set; }
    public decimal? QtyRent { get; set; }
    public decimal? TotalVal { get; set; }
    public decimal? TotalCost { get; set; }
    public decimal? UniteCost { get; set; }
    public string? EnName { get; set; }
    public string? FrName { get; set; }
    public string? UrName { get; set; }
    public string? TuName { get; set; }
    public string? RoName { get; set; }
    public string? ChName { get; set; }
    public string? RuName { get; set; }
    public Guid Rowguid { get; set; }
}
