namespace DataAccess.Domain.Models;

public class BillItemsSearchView
{
    public decimal? QtyIn { get; set; }
    public decimal? QtyOut { get; set; }
    public decimal? TotalVal { get; set; }
    public decimal? Qty1In { get; set; }
    public decimal? Qty1Out { get; set; }
    public decimal? Qty2In { get; set; }
    public decimal? Qty2Out { get; set; }
    public decimal? CostIn { get; set; }
    public decimal? CostOut { get; set; }
    public decimal? KindCost { get; set; }
    public decimal? Minimum { get; set; }
    public decimal? Maximum { get; set; }
    public decimal? FixedSale { get; set; }
    public string? Address { get; set; }
    public string? Address1 { get; set; }
    public string? Address2 { get; set; }
    public decimal? LinPrice { get; set; }
    public DateTime? Lindt { get; set; }
    public decimal? LinQty { get; set; }
    public string? LinUnite { get; set; }
    public decimal? LoutPrice { get; set; }
    public DateTime? LoutDt { get; set; }
    public decimal? LoutQty { get; set; }
    public string? LoutUnite { get; set; }
    public decimal? OrderCounts { get; set; }
    public decimal? Quote { get; set; }
    public decimal? Ordered { get; set; }
    public decimal? Requested { get; set; }
    public decimal? Reserved { get; set; }
    public decimal? TransferNeed { get; set; }
    public decimal? TransferAsk { get; set; }
    public string? GroupName { get; set; }
    public string? GroupCode { get; set; }
    public string? ItemType { get; set; }
    public string? VendorName { get; set; }
    public string? ItemName { get; set; }
    public string? ItemNameEn { get; set; }
    public string? ItemDescription { get; set; }
    public int? SliceId { get; set; }
    public int? SaleId { get; set; }
    public int? SaleCostId { get; set; }
    public int? OperatingId { get; set; }
    public int? SaleReturnId { get; set; }
    public decimal? ItemTax { get; set; }
    public bool? HasZeroTax { get; set; }
    public decimal? Discountbuy { get; set; }
    public decimal? Discountsale { get; set; }
    public bool? Active { get; set; }
    public string PricingMode { get; set; } = null!;
    public string? ItemTxt1 { get; set; }
    public string? ItemTxt2 { get; set; }
    public string? ItemTxt3 { get; set; }
    public string? ItemTxt4 { get; set; }
    public string? ItemTxt5 { get; set; }
    public string? ItemTxt6 { get; set; }
    public string? ItemTxt7 { get; set; }
    public string? ItemTxt8 { get; set; }
    public decimal? Serialcount { get; set; }
    public decimal? GuaranteePeriod { get; set; }
    public bool? IsExp { get; set; }
    public int? IdentityUnite { get; set; }
    public int? Size { get; set; }
    public int? Color { get; set; }
    public bool? HasEquation { get; set; }
    public bool? IsFreez { get; set; }
    public bool? CanReturn { get; set; }
    public int? ScId { get; set; }
    public int? UsageId { get; set; }
    public bool? IsOperate { get; set; }
    public int? ExprFormat { get; set; }
    public int? ExprMin { get; set; }
    public decimal? RewardPoint { get; set; }
    public bool? RewardCanReplace { get; set; }
    public int? RewardReplacePoint { get; set; }
    public decimal? Kupurchase { get; set; }
    public decimal? KuSale { get; set; }
    public decimal? Price1 { get; set; }
    public decimal? Price2 { get; set; }
    public decimal? Price3 { get; set; }
    public decimal? Price4 { get; set; }
    public decimal? Price5 { get; set; }
    public decimal? Price6 { get; set; }
    public decimal? Price7 { get; set; }
    public decimal? Price8 { get; set; }
    public string? VendorCode { get; set; }
    public string? StoreName { get; set; }
    public string? TaxName { get; set; }
    public string? Customer { get; set; }
    public string? CustomerGroup { get; set; }
    public string? CostCenter { get; set; }
    public string? RepMan { get; set; }
    public string? ToStore { get; set; }
    public int Id { get; set; }
    public int? BillIndex { get; set; }
    public string? Num { get; set; }
    public DateTime? Dt { get; set; }
    public string? ItemCode { get; set; }
    public decimal? ItemCost { get; set; }
    public string? Ship { get; set; }
    public decimal? Qty { get; set; }
    public decimal? Qty1 { get; set; }
    public decimal? Qty2 { get; set; }
    public string? Unite { get; set; }
    public decimal? Price { get; set; }
    public decimal? PriceAfterDiscount { get; set; }
    public decimal? NetPrice { get; set; }
    public decimal? Total { get; set; }
    public decimal? NetTotal { get; set; }
    public bool? Isfree { get; set; }
    public decimal? Bounes { get; set; }
    public decimal? ExtraCostPerc { get; set; }
    public decimal? ExtraCost { get; set; }
    public decimal? BillExtra { get; set; }
    public bool? Isdiscountperc { get; set; }
    public decimal? DiscountPerc { get; set; }
    public decimal? Discount { get; set; }
    public bool? Discountable { get; set; }
    public decimal? DiscountCashPerc { get; set; }
    public decimal? DiscountCash { get; set; }
    public decimal? DiscountTrade { get; set; }
    public decimal? DiscountGroup { get; set; }
    public int? Taxable { get; set; }
    public decimal? TaxPerc { get; set; }
    public decimal? Tax { get; set; }
    public int? IsDat { get; set; }
    public decimal? Datperc { get; set; }
    public decimal? Dat { get; set; }
    public string? Operate { get; set; }
    public DateTime? ExprDt { get; set; }
    public decimal? TotalDiscount { get; set; }
    public decimal? TotalExtra { get; set; }
    public decimal? SalePrice { get; set; }
    public string? TempSerial { get; set; }
    public decimal? Quota { get; set; }
    public string? Currency { get; set; }
    public decimal? Rate { get; set; }
    public decimal? RegNum { get; set; }
    public decimal? TaskId { get; set; }
    public decimal? TotalQty { get; set; }
    public bool? IsPaid { get; set; }
    public decimal? DisountBounesPerc { get; set; }
    public decimal? DisountBounes { get; set; }
    public decimal? UniteQty { get; set; }
    public string? InvoiceTxt1 { get; set; }
    public string? InvoiceTxt2 { get; set; }
    public string? InvoiceTxt3 { get; set; }
    public string? InvoiceTxt4 { get; set; }
    public string? InvoiceTxt5 { get; set; }
    public string? InvoiceTxt6 { get; set; }
    public string? InvoiceTxt7 { get; set; }
    public string? InvoiceTxt8 { get; set; }
    public decimal? DiscountPormotion { get; set; }
    public decimal? ExtraPormotion { get; set; }
    public decimal? ToStoreId { get; set; }
    public DateTime? DtImport { get; set; }
    public int? RepId { get; set; }
    public bool? RepDone { get; set; }
    public bool? RepVendorDone { get; set; }
    public decimal? ItemPoints { get; set; }
    public decimal? RewardPoints { get; set; }
    public int? AccountId { get; set; }
    public decimal? DiscountAfterTax { get; set; }
    public bool? PriceIncludeTax { get; set; }
    public int? RowId { get; set; }
    public decimal? ChargeDiscount { get; set; }
    public decimal? ChargeDiscountPerc { get; set; }
}