namespace DataAccess.Domain.Models;

public class FactoreOut
{
    public decimal Id { get; set; }
    public int? Dafter { get; set; }
    public int? BillIndex { get; set; }
    public int? Num { get; set; }
    public DateTime? Dt { get; set; }
    public string? Store { get; set; }
    public int? CustId { get; set; }
    public int? Workid { get; set; }
    public decimal? WorkPerc { get; set; }
    public decimal? WorkValue { get; set; }
    public string? Ship { get; set; }
    public string? ShipManager { get; set; }
    public string? ShipAdress { get; set; }
    public string? ShipPhone1 { get; set; }
    public string? ShipPhone2 { get; set; }
    public string? ShipVia { get; set; }
    public decimal? ShipTerms { get; set; }
    public DateTime? ShipDue { get; set; }
    public decimal? PoNumber { get; set; }
    public decimal? Renum { get; set; }
    public string? Currency { get; set; }
    public decimal? Rate { get; set; }
    public decimal? CurrencyTotal { get; set; }
    public bool? Isacc { get; set; }
    public string? WrittenBy { get; set; }
    public decimal? ItemTotal { get; set; }
    public decimal? BillDiscount { get; set; }
    public int? BillDiscountId { get; set; }
    public decimal? DiscountItem { get; set; }
    public decimal? DiscountItemId { get; set; }
    public decimal? BillTax { get; set; }
    public int? BillTaxId { get; set; }
    public decimal? BillExtraCost { get; set; }
    public int? BillExtraCostId { get; set; }
    public decimal? BillDatperc { get; set; }
    public decimal? BillDat { get; set; }
    public int? BillDatid { get; set; }
    public decimal? BillItemExtraCostPerc { get; set; }
    public decimal? BillItemExtraCost { get; set; }
    public int? BillItemExtraCostId { get; set; }
    public decimal? Money { get; set; }
    public decimal? MoneyId { get; set; }
    public decimal? Visa { get; set; }
    public decimal? VisaId { get; set; }
    public decimal? VisaPerc { get; set; }
    public decimal? VisaDiscountid { get; set; }
    public decimal? VisaExtra { get; set; }
    public decimal? Checks { get; set; }
    public decimal? BankId { get; set; }
    public decimal? Total { get; set; }
    public decimal? MoneyRemain { get; set; }
    public decimal? Remain { get; set; }
    public decimal? Totalmoney { get; set; }
    public decimal? Totalextra { get; set; }
    public decimal? Totaldiscount { get; set; }
    public decimal? SumBill { get; set; }
    public decimal? DiscountAcc { get; set; }
    public decimal? RegNum { get; set; }
    public decimal? ItemCount { get; set; }
    public string? Note { get; set; }
    public decimal? BranchId { get; set; }
    public bool? Ispaid { get; set; }
    public int? Iscash { get; set; }
    public decimal? TaxExtra { get; set; }
    public decimal? TaxExtraPerc { get; set; }
    public decimal? TaxExtraid { get; set; }
    public bool? IsIn { get; set; }
    public bool? IsStore { get; set; }
    public bool? IsGift { get; set; }
    public decimal? MoneyTotalPaid { get; set; }
    public decimal? DiscountDue { get; set; }
    public decimal? DiscountItemBounes { get; set; }
    public decimal? PeriodId { get; set; }
    public decimal? Cpu { get; set; }
    public decimal? RecievedMoney { get; set; }
    public decimal? PointsDiscount { get; set; }
    public Guid Rowguid { get; set; }
}
