namespace DataAccess.Domain.Models;

public partial class FactoreGo
{
    public decimal Id { get; set; }
    public decimal? Fromid { get; set; }
    public decimal? Toid { get; set; }
    public decimal? Idsale { get; set; }
    public decimal? Idsalecost { get; set; }
    public decimal? Salecost { get; set; }
    public DateTime? Dt { get; set; }
    public decimal? BillIndex { get; set; }
    public decimal? Dafter { get; set; }
    public string? Represent { get; set; }
    public string? TheUser { get; set; }
    public decimal? Num { get; set; }
    public decimal? Custid { get; set; }
    public string? Stock { get; set; }
    public decimal? Kindid { get; set; }
    public decimal? ValUnite { get; set; }
    public string? Unite { get; set; }
    public decimal? Price { get; set; }
    public string? Unite1 { get; set; }
    public decimal? ValUnite1 { get; set; }
    public bool? Taxable { get; set; }
    public decimal? Taxperc { get; set; }
    public decimal? TaxValue { get; set; }
    public decimal? Discount { get; set; }
    public string? Discountkindperc { get; set; }
    public decimal? Discountkind { get; set; }
    public decimal? Discountperc { get; set; }
    public decimal? Mountextra { get; set; }
    public decimal? Moneyextra { get; set; }
    public decimal? Money { get; set; }
    public decimal? TotalCur { get; set; }
    public decimal? Total { get; set; }
    public string? Note { get; set; }
    public decimal? Remain { get; set; }
    public decimal? Spend { get; set; }
    public decimal? Checks { get; set; }
    public bool? Isdue { get; set; }
    public DateTime? DueDate { get; set; }
    public string? DueNote { get; set; }
    public string? TaxGroup { get; set; }
    public DateTime? Expdt { get; set; }
    public bool? Active { get; set; }
    public string? Currency { get; set; }
    public decimal? Rate { get; set; }
    public string? Serial { get; set; }
    public string? Operate { get; set; }
    public string? Type { get; set; }
    public decimal? Dat { get; set; }
    public decimal? DatPercent { get; set; }
    public decimal? Regnum { get; set; }
    public decimal? Buy2 { get; set; }
    public decimal? Buy3 { get; set; }
    public decimal? Maxvalue { get; set; }
    public bool? Isdeleted { get; set; }
    public decimal? Kindcost { get; set; }
    public string? DiscountCurrent { get; set; }
    public decimal? DiscountCurrentval { get; set; }
    public decimal? DiscountCurrentTotal { get; set; }
    public string? Ship { get; set; }
    public bool? Recieved { get; set; }
    public DateTime? RecievedDt { get; set; }
    public decimal? Discountid { get; set; }
    public decimal? Extraid { get; set; }
    public decimal? Custaccountid { get; set; }
    public decimal? Exprid { get; set; }
    public decimal? Discountitemid { get; set; }
    public decimal? Discountitem { get; set; }
    public string? Tempserial { get; set; }
    public string? Tempserial1 { get; set; }
    public decimal? DueDiscount { get; set; }
    public decimal? DuePaid { get; set; }
    public decimal? Taxid { get; set; }
    public bool? Custdis { get; set; }
    public string? Machine { get; set; }
    public Guid Rowguid { get; set; }
}
