namespace DataAccess.Domain.Models;

public partial class FixedAsset
{
    public long Id { get; set; }
    public int? BranchId { get; set; }
    public DateTime? Dt { get; set; }
    public string? Dthijri { get; set; }
    public string? Dafter { get; set; }
    public int? Num { get; set; }
    public string? Code { get; set; }
    public string? ArName { get; set; }
    public string? EnName { get; set; }
    public string? FrName { get; set; }
    public string? UrName { get; set; }
    public string? TuName { get; set; }
    public string? RoName { get; set; }
    public string? ChName { get; set; }
    public string? RuName { get; set; }
    public DateTime? DtUsed { get; set; }
    public int? GroupId { get; set; }
    public bool? Active { get; set; }
    public bool? IsDep { get; set; }
    public int? CostId { get; set; }
    public decimal? QtyIn { get; set; }
    public decimal? QtyOut { get; set; }
    public decimal? QtyRent { get; set; }
    public decimal? Qty { get; set; }
    public decimal? AssetCostIn { get; set; }
    public decimal? AssetCostOut { get; set; }
    public decimal? AssetCostTotal { get; set; }
    public string? Currency { get; set; }
    public decimal? Rate { get; set; }
    public int? DepreciationId { get; set; }
    public bool? Sale { get; set; }
    public bool? Rent { get; set; }
    public bool? Maintenance { get; set; }
    public int? AccountId { get; set; }
    public int? CapitalId { get; set; }
    public string? CountryManufacture { get; set; }
    public string? ManufacturingCompany { get; set; }
    public string? EmpName { get; set; }
    public string? Length { get; set; }
    public string? Width { get; set; }
    public string? Height { get; set; }
    public int? LicenseNum { get; set; }
    public int? CarNum { get; set; }
    public int? SerialNum { get; set; }
    public int? InsuranceNum { get; set; }
    public string? Model { get; set; }
    public string? Color { get; set; }
    public DateTime? DtLicenseExpiration { get; set; }
    public DateTime? DtExamination { get; set; }
    public string? Address { get; set; }
    public string? Neighbour1 { get; set; }
    public string? Neighbour2 { get; set; }
    public string? Neighbour3 { get; set; }
    public string? Area { get; set; }
    public string? Store { get; set; }
    public string? Room { get; set; }
    public int? RackNum { get; set; }
    public int? DepreciationPeriod { get; set; }
    public bool? IsFixedRatio { get; set; }
    public decimal? DepreciationRatio { get; set; }
    public decimal? DepreciationScrapValue { get; set; }
    public int? DestroyId { get; set; }
    public int? DestoryDiscountId { get; set; }
    public int? ProfitsId { get; set; }
    public int? LossesId { get; set; }
    public int? RecalcFlowId { get; set; }
    public int? OtherInsurancesId { get; set; }
    public int? RentAccountId { get; set; }
    public decimal? DeprecateCenterIn { get; set; }
    public decimal? DeprecateCenterOut { get; set; }
    public decimal? DeprecateCenterTotal { get; set; }
    public decimal? Price { get; set; }
    public string? Txt1 { get; set; }
    public string? Txt2 { get; set; }
    public string? Txt3 { get; set; }
    public string? Txt4 { get; set; }
    public string? Txt5 { get; set; }
    public string? Txt6 { get; set; }
    public string? Txt7 { get; set; }
    public string? Txt8 { get; set; }
    public decimal? TaskId { get; set; }
    public string? WrittenBy { get; set; }
    public DateTime? LstUpdate { get; set; }
    public string? UpdatedBy { get; set; }
    public bool? Attached { get; set; }
    public Guid Rowguid { get; set; }
}
