namespace DataAccess.Domain.Models;

public partial class ItemSearch
{
    public int? Id { get; set; }
    public int? StoreId { get; set; }
    public int? KindId { get; set; }
    public DateTime? Dt { get; set; }
    public int? ParentId { get; set; }
    public int? TypeIndex { get; set; }
    public int? Optkind { get; set; }
    public string? ArName { get; set; }
    public string? EnName { get; set; }
    public string? FrName { get; set; }
    public string? UrName { get; set; }
    public string? TuName { get; set; }
    public string? RoName { get; set; }
    public string? ChName { get; set; }
    public string? RuName { get; set; }
    public string? Ship { get; set; }
    public int? Taxable { get; set; }
    public bool? HasEquation { get; set; }
    public int? ComId { get; set; }
    public decimal? Tax { get; set; }
    public bool? HasZeroTax { get; set; }
    public bool? PriceIncludeTax { get; set; }
    public bool? Discountable { get; set; }
    public bool? Isdiscountperc { get; set; }
    public decimal? Discountbuy { get; set; }
    public decimal? Discountsale { get; set; }
    public bool? Active { get; set; }
    public decimal? Moneyextra { get; set; }
    public string? Txt1 { get; set; }
    public string? Txt2 { get; set; }
    public string? Txt3 { get; set; }
    public string? Txt4 { get; set; }
    public string? Txt5 { get; set; }
    public int? PricingMode { get; set; }
    public decimal? Kindindex { get; set; }
    public string? Txt6 { get; set; }
    public string? Txt7 { get; set; }
    public string? Txt8 { get; set; }
    public decimal? Serialcount { get; set; }
    public decimal? GuaranteePeriod { get; set; }
    public bool? IsExp { get; set; }
    public int? IdentityUnite { get; set; }
    public int? Size { get; set; }
    public int? Color { get; set; }
    public int? VendorId { get; set; }
    public bool? HideFromTouch { get; set; }
    public int? AccountId { get; set; }
    public int? SaleId { get; set; }
    public int? SaleCostId { get; set; }
    public int? SaleReturnId { get; set; }
    public decimal? FixedCost { get; set; }
    public int? OperatingId { get; set; }
    public int? CapitalId { get; set; }
    public decimal? QtyIn { get; set; }
    public decimal? QtyOut { get; set; }
    public decimal? TotalVal { get; set; }
    public decimal? Qty1In { get; set; }
    public decimal? Qty1Out { get; set; }
    public decimal? Qty2In { get; set; }
    public decimal? Qty2Out { get; set; }
    public decimal? CostIn { get; set; }
    public decimal? CostOut { get; set; }
    public decimal? KindCost { get; set; }
    public decimal? OpenBalance { get; set; }
    public int? SliceId { get; set; }
    public decimal? RewardPoint { get; set; }
    public decimal? OpenCost { get; set; }
    public string? OpenUnite { get; set; }
    public decimal? OpenRegNum { get; set; }
    public decimal? OpenTaskId { get; set; }
    public decimal? OpenQty1 { get; set; }
    public decimal? OpenQty2 { get; set; }
    public decimal? Minimum { get; set; }
    public decimal? Maximum { get; set; }
    public decimal? FixedSale { get; set; }
    public decimal? ExprDt { get; set; }
    public string? Address { get; set; }
    public string? Address1 { get; set; }
    public string? Address2 { get; set; }
    public decimal? LinPrice { get; set; }
    public DateTime? Lindt { get; set; }
    public decimal? LinQty { get; set; }
    public string? LinUnite { get; set; }
    public decimal? LoutPrice { get; set; }
    public DateTime? LoutDt { get; set; }
    public decimal? LoutQty { get; set; }
    public string? LoutUnite { get; set; }
    public string? Code { get; set; }
    public string? Unite { get; set; }
    public string? Currency { get; set; }
    public decimal? UniteQty { get; set; }
    public decimal? Buy { get; set; }
    public decimal? Sale { get; set; }
    public decimal? Price1 { get; set; }
    public decimal? Price2 { get; set; }
    public decimal? Price3 { get; set; }
    public decimal? Price4 { get; set; }
    public decimal? Price5 { get; set; }
    public decimal? Price6 { get; set; }
    public decimal? Price7 { get; set; }
    public decimal? Price8 { get; set; }
    public bool? Masterbuy { get; set; }
    public bool? Mastersale { get; set; }
    public decimal? Levels { get; set; }
    public string? ArNameG { get; set; }
    public string? EnNameG { get; set; }
    public string? FrNameG { get; set; }
    public string? UrNameG { get; set; }
    public string? TuNameG { get; set; }
    public string? RoNameG { get; set; }
    public string? ChNameG { get; set; }
    public string? RuNameG { get; set; }
    public string? ArNameO { get; set; }
    public string? EnNameO { get; set; }
    public int? DatTaxable { get; set; }
    public int? DatId { get; set; }
    public decimal? DatPerc { get; set; }
    public string? Gstype { get; set; }
    public string? KindBarcode { get; set; }
    public string? FrNameO { get; set; }
    public string? UrNameO { get; set; }
    public string? TuNameO { get; set; }
    public string? RoNameO { get; set; }
    public string? ChNameO { get; set; }
    public string? RuNameO { get; set; }
    public string? Store { get; set; }
    public string? OpenSerial { get; set; }
    public bool? IsOperate { get; set; }
    public int? ExprMin { get; set; }
    public int? ExprFormat { get; set; }
    public bool? Checked { get; set; }
    public int? VisibleOrder { get; set; }
    public int? ForeColor { get; set; }
    public int? TaxId { get; set; }
    public decimal? Saletax { get; set; }
    public decimal? PurchaseTax { get; set; }
    public string? Gpccode { get; set; }
    public DateTime? ActiveFrom { get; set; }
}
