namespace DataAccess.Domain.Models;

public partial class PurchaseImport
{
    public decimal Id { get; set; }
    public int? Dafter { get; set; }
    public int? BillIndex { get; set; }
    public int? Num { get; set; }
    public DateTime? Dt { get; set; }
    public decimal? StoreId { get; set; }
    public int? CustId { get; set; }
    public int? RepId { get; set; }
    public bool? RepDone { get; set; }
    public decimal? RepTaskId { get; set; }
    public string? Ship { get; set; }
    public string? ShipManager { get; set; }
    public string? ShipAdress { get; set; }
    public string? ShipPhone1 { get; set; }
    public string? ShipPhone2 { get; set; }
    public string? ShipVia { get; set; }
    public decimal? ShipTerms { get; set; }
    public DateTime? ShipDue { get; set; }
    public decimal? PoNumber { get; set; }
    public decimal? Renum { get; set; }
    public string? Currency { get; set; }
    public decimal? Rate { get; set; }
    public decimal? CurrencyTotal { get; set; }
    public bool? Isacc { get; set; }
    public string? WrittenBy { get; set; }
    public decimal? ItemTotal { get; set; }
    public decimal? BillDiscount { get; set; }
    public int? BillDiscountId { get; set; }
    public decimal? DiscountItem { get; set; }
    public decimal? DiscountItemId { get; set; }
    public decimal? BillTax { get; set; }
    public int? BillTaxId { get; set; }
    public decimal? BillTaxPerc { get; set; }
    public decimal? BillExtraCost { get; set; }
    public int? BillExtraCostId { get; set; }
    public decimal? BillDatperc { get; set; }
    public decimal? BillDat { get; set; }
    public int? BillDatid { get; set; }
    public decimal? BillItemExtraCostPerc { get; set; }
    public decimal? BillItemExtraCost { get; set; }
    public int? BillItemExtraCostId { get; set; }
    public decimal? Money { get; set; }
    public decimal? MoneyId { get; set; }
    public decimal? Visa { get; set; }
    public decimal? VisaId { get; set; }
    public decimal? Checks { get; set; }
    public decimal? CheckBankId { get; set; }
    public decimal? Bank { get; set; }
    public decimal? BankId { get; set; }
    public decimal? Pledge { get; set; }
    public decimal? Account { get; set; }
    public decimal? Accountid { get; set; }
    public decimal? Installment { get; set; }
    public decimal? Total { get; set; }
    public decimal? MoneyRemain { get; set; }
    public decimal? Remain { get; set; }
    public decimal? Totalmoney { get; set; }
    public decimal? Totalextra { get; set; }
    public decimal? Totaldiscount { get; set; }
    public decimal? SumBill { get; set; }
    public decimal? DiscountAcc { get; set; }
    public decimal? RegNum { get; set; }
    public decimal? ItemCount { get; set; }
    public string? Note { get; set; }
    public int? IsCash { get; set; }
    public bool? IsPaid { get; set; }
    public decimal? BranchId { get; set; }
    public DateTime? PaidDt { get; set; }
    public decimal? PaidValue { get; set; }
    public decimal? PaidDisount { get; set; }
    public decimal? PaidRegNum { get; set; }
    public decimal? PaidNum { get; set; }
    public decimal? TaxExtra { get; set; }
    public decimal? TaxExtraPerc { get; set; }
    public decimal? TaxExtraid { get; set; }
    public int? Cpu { get; set; }
    public int? PeriodId { get; set; }
    public decimal? MoneyTotalPaid { get; set; }
    public decimal? DiscountDue { get; set; }
    public decimal? DiscountItemBounes { get; set; }
    public decimal? DiscountItemBounesId { get; set; }
    public decimal? DayIndex { get; set; }
    public decimal? Type { get; set; }
    public string? Txt1 { get; set; }
    public string? Txt2 { get; set; }
    public string? Txt3 { get; set; }
    public string? Txt4 { get; set; }
    public string? Txt5 { get; set; }
    public string? Txt6 { get; set; }
    public string? Txt7 { get; set; }
    public string? Txt8 { get; set; }
    public decimal? ClassId { get; set; }
    public decimal? Rep3 { get; set; }
    public decimal? Rep2 { get; set; }
    public decimal? TaxType { get; set; }
    public decimal? WorkRegNum { get; set; }
    public bool? IsIn { get; set; }
    public bool? IsDone { get; set; }
    public decimal? OtherPayment { get; set; }
    public decimal? RecievedMoney { get; set; }
    public decimal? PointsDiscount { get; set; }
    public Guid Rowguid { get; set; }
}
