namespace DataAccess.Domain.Models;

/// <summary>
/// اسماء و بيانات الموظفين
/// </summary>
public partial class Work
{
    public int Id { get; set; }
    public int? Num { get; set; }
    public string? ArName { get; set; }
    public string? EnName { get; set; }
    public string? FrName { get; set; }
    public string? UrName { get; set; }
    public string? TuName { get; set; }
    public string? RoName { get; set; }
    public string? ChName { get; set; }
    public string? RuName { get; set; }
    public int? Status { get; set; }
    public int? BranchId { get; set; }
    public string? Sex { get; set; }
    public DateTime? BornDt { get; set; }
    public int? NationalityId { get; set; }
    public int? MaritalStatusId { get; set; }
    public int? BloodTypeId { get; set; }
    public int? FacultyId { get; set; }
    public int? GraduationYear { get; set; }
    public DateTime? HiringDate { get; set; }
    public int? DepartmentId { get; set; }
    public int? SectorId { get; set; }
    public int? JobId { get; set; }
    public int? SalaryGroupId { get; set; }
    public string? DriverLicense { get; set; }
    public string? PersonalId { get; set; }
    public string? Mobile1 { get; set; }
    public string? Mobile2 { get; set; }
    public string? Phone { get; set; }
    public string? Mail { get; set; }
    public string? Address { get; set; }
    public bool? IsFamily { get; set; }
    public int? Sons { get; set; }
    public int? Dependents { get; set; }
    public int? Students { get; set; }
    public decimal? Rent { get; set; }
    public int? DirectManagerId { get; set; }
    public int? Sliceid { get; set; }
    public int? PeriodId { get; set; }
    public int? GroupId { get; set; }
    public int? PayrollScheduleId { get; set; }
    public int? PaymentMethod { get; set; }
    public bool? HasAttendance { get; set; }
    public bool? IsRep { get; set; }
    public bool? IsPledge { get; set; }
    public int? GpagradeId { get; set; }
    public string? ContractState { get; set; }
    public string? JobState { get; set; }
    public bool? Istax { get; set; }
    public bool? Isinsurance { get; set; }
    public int? InsurancType { get; set; }
    public decimal? InsurancePreFixValue { get; set; }
    public decimal? InsurancePreChangedValue { get; set; }
    public string? InsuranceNum { get; set; }
    public string? InsuranceCo { get; set; }
    public decimal? InsuranceWorkFixed { get; set; }
    public decimal? InsuranceWorkChanged { get; set; }
    public decimal? InsuranceCoFixed { get; set; }
    public decimal? InsuranceCoChanged { get; set; }
    public string? Txt1 { get; set; }
    public string? Txt2 { get; set; }
    public string? Txt3 { get; set; }
    public string? Txt4 { get; set; }
    public string? Txt5 { get; set; }
    public string? Txt6 { get; set; }
    public string? Txt7 { get; set; }
    public string? Txt8 { get; set; }
    public int? MaxSolfa { get; set; }
    public decimal? Raseedkhasm { get; set; }
    public decimal? Raseed { get; set; }
    public bool? Iscredit { get; set; }
    public int? SalaryId { get; set; }
    public int? CapitalId { get; set; }
    public string? CarNum { get; set; }
    public string? CarKind { get; set; }
    public decimal? Debit { get; set; }
    public decimal? Credit { get; set; }
    public decimal? Balance { get; set; }
    public decimal? Hisdebit { get; set; }
    public decimal? Hiscredit { get; set; }
    public decimal? Hisbalance { get; set; }
    public decimal? Gasraseed { get; set; }
    public bool? Fixedsale { get; set; }
    public bool? IssalePercent { get; set; }
    public decimal? Salepercent { get; set; }
    public decimal? Timevalue { get; set; }
    public decimal? Regnum { get; set; }
    public decimal? ResidencePeriod { get; set; }
    public decimal? Rate { get; set; }
    public decimal? TotalSalary { get; set; }
    public decimal? AbsentRate { get; set; }
    public decimal? TotalDebit { get; set; }
    public string? PeriodGroup { get; set; }
    public decimal? TotalPledgeDebit { get; set; }
    public decimal? TotalPledgeCredit { get; set; }
    public bool? Refusal { get; set; }
    public bool? Leave { get; set; }
    public bool? StopSalary { get; set; }
    public string? BankAccount { get; set; }
    public decimal? TaskId { get; set; }
    public int? WorkIn { get; set; }
    public int? FacLevel { get; set; }
    public decimal? ServiceDebit { get; set; }
    public decimal? ServiceCredit { get; set; }
    public int? CostId { get; set; }
    public bool? DeliveryStatus { get; set; }
    public Guid Rowguid { get; set; }
}
